[features]
resolution = true
skip-lint = false

[programs.devnet]
sol_auto_saving = "BKJ552hX7xU4KXYDaduug9mHLdSDiPX7xCcUtUSGJhL4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
[toolchain]
anchor_version = "0.26.0"
